#!/bin/bash

# it expects to have a directory bct_live where to create the ISO
# beware this requires sth like 1Gb of free disk
cd bct_live || exit 1
sudo lh clean
sudo rm -rf config

# lenny
# doesn't feature "haveged" so the package was retrieved from sid and left in create_iso/content_for_bct_iso/chroot_local-packages/haveged_0.9-2_i386.deb
sudo lh config --cache true --binary-images iso --distribution lenny --architecture i386 --hostname bct-live --packages "gnupg gnupg-doc gnupg-agent python-gnupginterface gnupg2 ssss pgpdump wipe randomsound"

# squeeze
# !! currently broken, see http://debian-live.alioth.debian.org/
#sudo lh config --cache true --binary-images iso --distribution squeeze --architecture i386 --hostname bct-live --packages "gnupg gnupg-doc gnupg-agent python-gnupginterface gnupg2 ssss pgpdump wipe randomsound haveged"
sudo cp -a ../content_for_bct_iso/* config/
sudo lh build
